### ISSUE TITLE
Logovat zakládání jobu do PT

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-component-bundle#26]
V moment založení jobu by se v logu mělo objevit jeho id, id SQS message a jméno SQS fronty do které byl vložen.

**Comment by MiroCillik** [comment]
https://github.com/keboola/syrup-component-bundle/blob/master/Controller/ApiController.php#L63

**Comment by Halama** [comment]
Přečetl sis vůbec text toho ticketu?

**Comment by Halama** [comment]
jo aha to nebyl link na commit https://github.com/keboola/syrup-component-bundle/commit/5f399e8a71ae0a67e63585d7f644520c4778a4b3#diff-64468bbc5a4a07225094e252e10286ec

Stejně tam ale chybí to message id a zbytečně se to tam loguje třikrát místo toho aby se to zalogovalo jednou se všema informacema které jsou teda:

 * id jobu
 * id SQS message
 * jméno fronty

**Comment by MiroCillik** [comment]
ja som to schvalne rozdelil, aby bolo vidiet na com to spadlo pripadne.. Ale asi je to zbytocne.. takze takto: https://github.com/keboola/syrup-component-bundle/commit/e9fa87be13f22bf0e5372608d9fdf1e941507806

**Comment by Halama** [comment]
Ty jo ted koukam ze to leze do SAPI eventu tam by to urcite byt nemelo. Je to pro debug, kdyz resime proc se nekde nespustil job apod.
