### ISSUE TITLE
Id jobu se pořád vrací jako string

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-component-bundle#27]
Už se to myslím řešilo, prosím ověřit. Musí to být integer.
https://www.evernote.com/shard/s31/sh/b80bf3f8-cd61-4022-8384-c8b0d6885fb5/a6e6d3e6c77e7c0c5f1b1e6abde395a8/deep/0/Postman.png

**Comment by MiroCillik** [comment]
aha, to mozno bude tym, ze syrup-queue nie je na najnovsom SCB.. Mrknem na
to

**Comment by MiroCillik** [comment]
uz by to malo byt vsade upravene aj tu https://github.com/keboola/syrup-component-bundle/blob/master/Resources/views/Elasticsearch/mappingDefault.json.twig#L25 aj syrup-queue v controlleri
