### ISSUE TITLE
Interní věci v API odpovědi jobu

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-component-bundle#28]
https://www.evernote.com/shard/s31/sh/e8e78dc6-0f63-4ca5-aa16-fec134adb1d1/c68400abd47189622d3e0c7980677cc2/deep/0/Postman.png

Ty přeškrtaný věci tam nemusejí být.

**Comment by MiroCillik** [comment]
ten _index a _type je tam schvalne, ked chces killnut job aby si vedel na
akom indexe.. ked bude na killovanie jobu nejaky command tak to mozme
vyhodit
