### ISSUE TITLE
zpracování aplikačních chyb - probublávání do eventů

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup-component-bundle#32]
Pokud v Executoru vyhodím \Exception, je to správně braný jako aplikační chyba, ale její hláška probublává ven. V PaperTrailu je správně, ale probublá i do eventu v SAPI, tam by rozhodně být neměla.

Viz http://note.io/1trYQza

SCB 1.10.10, v commitech nevidím, že by to bylo dál opravený

**Comment by MiroCillik** [comment]
Bolo to opravene v 1.10.16 https://github.com/keboola/syrup-component-bundle/commit/5f67cc887cbdb028616c9b194b56ca1a04cff2f5
