### ISSUE TITLE
Úpravy v logování

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/syrup-component-bundle#41]
Co se týče implementace, momentálně to obsluhuje výchozí syslog handler a veškerá logika je v SyrupJsonFormatteru. Změnil bych to následovně: Logování do syslogu/PT a SAPI budou mít na starosti dva samostatné handlery (SyslogHandler a StorageApiHandler), ty zařídí i případný upload příloh do s3. Přidání dat do logu (token, job, request, apod.) zařizuje samostatný Processor. JsonFormatter na závěr už jen z pole udělá json, nic víc.

* U commandu přidat info jak byl spuštěn (např. `'cliCommand': './scripts/cli.php --ansi storage:queue:receive main_fast 14'`), u requestu url a parametry (např. `'http': { 'url': 'http://...', 'post': {'param1': 'value'}, 'ip': '...', 'userAgent': '...'}`)
* Přestat logovat bordel typu "Matched route"
* Příliš dlouhý log do PT zkrátit a nahrát do s3

**Comment by JakubMatejka** [comment]
U commandu přidat info jak byl spuštěn (např. `'cliCommand': './scripts/cli.php --ansi storage:queue:receive main_fast 14'`), u requestu url a parametry (např. `'http': { 'url': 'http://...', 'post': {'param1': 'value'}, 'ip': '...', 'userAgent': '...'}`)

**Comment by JakubMatejka** [comment]
Přestat logovat bordel typu "Matched route"

**Comment by JakubMatejka** [comment]
Příliš dlouhý log do PT zkrátit a nahrát do s3

**Comment by odinuv** [comment]
Bylo by fajn, kdyby zustala funkcni moznost logovat do souboru, dneska to delam nastavenim v configu:monolog:
    handlers:
        syslog:
            ident: %app_name%
            type: stream
            level: debug
            path: C:\\Temp\\Lg\\symfony.log
